# generated by datamodel-codegen:
#   filename:  rcon-openapispec.json
#   timestamp: 2026-09-08T14:00:12+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, Field


class Ok(BaseModel):
    ok: bool | None = None
    message: str | None = None


class Error1(BaseModel):
    code: str | None = None
    message: str | None = None


class Error(BaseModel):
    error: Error1 | None = None


class FactionScore(BaseModel):
    name: str | None = None
    colorHex: str | None = None
    score: int | None = None


class ScoreTick(BaseModel):
    current: int | None = None
    min: int | None = None
    max: int | None = None


class Players(BaseModel):
    current: int | None = None
    max: int | None = None


class Rotation(BaseModel):
    nowIndex: int | None = None
    nextIndex: int | None = None


class Status(BaseModel):
    serverName: str | None = None
    serverId: str | None = Field(default="7b4463f3-3f79-4c26-a5fd-781aedca2a16", alias="serverID")
    map: str | None = None
    experiences: list[str] | None = None
    lighting: str | None = None
    alternator: str | None = None
    scoreTick: ScoreTick | None = None
    scoreCap: int | None = None
    matchSeconds: int | None = None
    players: Players | None = None
    factionScores: list[FactionScore] | None = None
    rotation: Rotation | None = None


class Player(BaseModel):
    name: str | None = None
    steamId: str | None = None
    faction: str | None = None
    kills: int | None = None
    deaths: int | None = None
    cash: int | None = None
    pingMs: int | None = None


class Players1(BaseModel):
    players: list[Player] | None = None


class Config(BaseModel):
    writable: bool | None = None


class Capabilities(BaseModel):
    routes: list[str] | None = None
    config: Config | None = None



class ReservedSlots(BaseModel):
    reservedSlots: list[str] | None = None


class AuditEntry(BaseModel):
    timestampUtc: str | None = None
    peer: str | None = None
    sessionId: str | None = None
    event: str | None = None
    detail: str | None = None


class Audit(BaseModel):
    entries: list[AuditEntry] | None = None


class RotationEntry(BaseModel):
    map: str | None = None
    experiences: list[str] | None = None
    lighting: str | None = None
    zoneAlternator: str | None = None
    status: str | None = None
    denied: bool | None = None


class Rotation1(BaseModel):
    enabled: bool | None = None
    mode: str | None = None
    entries: list[RotationEntry] | None = None


class Catalog(BaseModel):
    pass


class Sponsor(BaseModel):
    imageUrl: str | None = None


class Config1(BaseModel):
    revision: str | None = None
    writable: bool | None = None
    text: str | None = None
    sections: list[dict[str, Any]] | None = None
    warnings: list[str] | None = None


class ConfigResult(BaseModel):
    ok: bool | None = None
    revision: str | None = None
    error: Error | None = None
    outcomes: list[Any] | None = None
    changed: list[Any] | None = None
    warnings: list[Any] | None = None


class MapSelection(BaseModel):
    map: str
    experiences: list[str] | None = None
    lighting: str | None = None
    zoneAlternator: str | None = None


class ReasonRequest(BaseModel):
    reason: str | None = None
    duration_days: int | None = None
    solo_discord: bool = False



class SteamIdRequest(BaseModel):
    steamId: str


class MessageRequest(BaseModel):
    message: str


class FactionRequest(BaseModel):
    faction: str


class LightingRequest(BaseModel):
    lighting: str


class Direction(Enum):
    up = 'up'
    down = 'down'


class MoveRequest(BaseModel):
    direction: Direction


class SettingsPatch(BaseModel):
    scoreTick: int | None = None
    rotationEnabled: bool | None = None
    rotationMode: str | None = None


class SponsorRequest(BaseModel):
    imageUrl: str



