"""Add role_type and DDD role schema

Revision ID: 0e7d9f2ccf83
Revises: 9ce85711e2cc
Create Date: 2026-09-17 07:39:07.519644

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0e7d9f2ccf83'
down_revision: str | Sequence[str] | None = '9ce85711e2cc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    insp = sa.inspect(bind)
    bans_cols = [c['name'] for c in insp.get_columns('bans')]
    if 'expires_at' not in bans_cols:
        op.add_column('bans', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    role_enum = sa.Enum('SYSTEM', 'VIP', 'PUNISHMENT', 'PUBLIC', name='roletype')
    role_enum.create(op.get_bind())
    op.add_column('roles', sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('roles', sa.Column('discord_role_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('roles', sa.Column('role_type', role_enum, nullable=True))
    
    # Data migration for the single existing Owner role
    op.execute(
        "UPDATE roles SET "
        "code = 'OWNER_MAIN', "
        "discord_role_id = name, "
        "name = 'Fundador Principal', "
        "role_type = 'SYSTEM' "
        "WHERE id = 1"
    )
    
    op.alter_column('roles', 'code', existing_type=sqlmodel.sql.sqltypes.AutoString(), nullable=False)
    op.alter_column('roles', 'role_type', existing_type=sa.Enum('SYSTEM', 'VIP', 'PUNISHMENT', 'PUBLIC', name='roletype'), nullable=False)
    op.alter_column('roles', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.create_index(op.f('ix_roles_code'), 'roles', ['code'], unique=True)
    op.create_index(op.f('ix_roles_discord_role_id'), 'roles', ['discord_role_id'], unique=False)
    op.create_index(op.f('ix_roles_role_type'), 'roles', ['role_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roles_role_type'), table_name='roles')
    
    sa.Enum(name='roletype').drop(op.get_bind(), checkfirst=False)
    op.drop_index(op.f('ix_roles_discord_role_id'), table_name='roles')
    op.drop_index(op.f('ix_roles_code'), table_name='roles')
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.alter_column('roles', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('roles', 'role_type')
    op.drop_column('roles', 'discord_role_id')
    op.drop_column('roles', 'code')
    op.drop_column('bans', 'expires_at')
    # ### end Alembic commands ###
