"""Add squads tables

Revision ID: 2281fd6205e6
Revises: 2c236beea135
Create Date: 2026-10-04 03:04:14.797864

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2281fd6205e6'
down_revision: str | Sequence[str] | None = '2c236beea135'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('squads',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tag', sqlmodel.sql.sqltypes.AutoString(length=4), nullable=False),
    sa.Column('leader_steam_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_kills', sa.Integer(), nullable=False),
    sa.Column('total_deaths', sa.Integer(), nullable=False),
    sa.Column('total_cash_earned', sa.Integer(), nullable=False),
    sa.Column('total_matches_played', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['leader_steam_id'], ['players.steam_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_squads_leader_steam_id'), 'squads', ['leader_steam_id'], unique=False)
    op.create_index(op.f('ix_squads_name'), 'squads', ['name'], unique=True)
    op.create_index(op.f('ix_squads_tag'), 'squads', ['tag'], unique=False)
    op.create_table('squad_invites',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('squad_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('inviter_steam_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('invitee_discord_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['inviter_steam_id'], ['players.steam_id'], ),
    sa.ForeignKeyConstraint(['squad_id'], ['squads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_squad_invites_invitee_discord_id'), 'squad_invites', ['invitee_discord_id'], unique=False)
    op.create_index(op.f('ix_squad_invites_squad_id'), 'squad_invites', ['squad_id'], unique=False)
    op.create_table('squad_members',
    sa.Column('squad_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('steam_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['squad_id'], ['squads.id'], ),
    sa.ForeignKeyConstraint(['steam_id'], ['players.steam_id'], ),
    sa.PrimaryKeyConstraint('squad_id', 'steam_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('squad_members')
    op.drop_index(op.f('ix_squad_invites_squad_id'), table_name='squad_invites')
    op.drop_index(op.f('ix_squad_invites_invitee_discord_id'), table_name='squad_invites')
    op.drop_table('squad_invites')
    op.drop_index(op.f('ix_squads_tag'), table_name='squads')
    op.drop_index(op.f('ix_squads_name'), table_name='squads')
    op.drop_index(op.f('ix_squads_leader_steam_id'), table_name='squads')
    op.drop_table('squads')
    # ### end Alembic commands ###
