"""add is_active and rcon_sync_status to bans

Revision ID: 47312279a0c3
Revises: db3ec4dfb58e
Create Date: 2026-09-13 16:08:39.336368

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '47312279a0c3'
down_revision: str | Sequence[str] | None = 'db3ec4dfb58e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bans', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('bans', sa.Column('rcon_sync_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bans', 'rcon_sync_status')
    op.drop_column('bans', 'is_active')
    # ### end Alembic commands ###
