"""Initial_Aware

Revision ID: 8711d6c5c582
Revises: 
Create Date: 2026-09-11 16:39:23.035494

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8711d6c5c582'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_config',
    sa.Column('config_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('config_value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('config_key')
    )
    op.create_table('players',
    sa.Column('steam_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('discord_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('custom_welcome_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('steam_id')
    )
    op.create_index(op.f('ix_players_discord_id'), 'players', ['discord_id'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('bans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('steam_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('banned_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['steam_id'], ['players.steam_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bans_steam_id'), 'bans', ['steam_id'], unique=False)
    op.create_table('matches',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('map_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('winning_team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['winning_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('steam_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('role_granted_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_granted_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['steam_id'], ['players.steam_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memberships_steam_id'), 'memberships', ['steam_id'], unique=False)
    op.create_index(op.f('ix_memberships_type'), 'memberships', ['type'], unique=False)
    op.create_table('player_roles',
    sa.Column('steam_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['steam_id'], ['players.steam_id'], ),
    sa.PrimaryKeyConstraint('steam_id', 'role_id')
    )
    op.create_table('match_player_stats',
    sa.Column('steam_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('match_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('kills', sa.Integer(), nullable=False),
    sa.Column('deaths', sa.Integer(), nullable=False),
    sa.Column('cash_spent', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['steam_id'], ['players.steam_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('steam_id', 'match_id')
    )
    op.create_table('match_team_stats',
    sa.Column('match_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('match_id', 'team_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match_team_stats')
    op.drop_table('match_player_stats')
    op.drop_table('player_roles')
    op.drop_index(op.f('ix_memberships_type'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_steam_id'), table_name='memberships')
    op.drop_table('memberships')
    op.drop_table('matches')
    op.drop_index(op.f('ix_bans_steam_id'), table_name='bans')
    op.drop_table('bans')
    op.drop_table('teams')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_players_discord_id'), table_name='players')
    op.drop_table('players')
    op.drop_table('bot_config')
    # ### end Alembic commands ###

