"""Remove bans and tebex

Revision ID: a82b4eba14e5
Revises: m9i0d1e2f3g4
Create Date: 2026-10-02 16:08:12.806784

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a82b4eba14e5'
down_revision: str | Sequence[str] | None = 'm9i0d1e2f3g4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()
    insp = sa.inspect(conn)
    tables = insp.get_table_names()

    if 'payment_records' in tables:
        for idx in ['ix_payment_records_discord_id', 'ix_payment_records_event_type', 'ix_payment_records_package_id', 'ix_payment_records_status', 'ix_payment_records_steam_id', 'ix_payment_records_transaction_id']:
            try:
                op.drop_index(op.f(idx), table_name='payment_records')
            except Exception:
                pass
        op.drop_table('payment_records')

    if 'bans' in tables:
        try:
            op.drop_index(op.f('ix_bans_steam_id'), table_name='bans')
        except Exception:
            pass
        op.drop_table('bans')

    if 'membership_types' in tables:
        mt_cols = [c['name'] for c in insp.get_columns('membership_types')]
        if 'base_price_usd' in mt_cols:
            op.drop_column('membership_types', 'base_price_usd')
        if 'tebex_package_id' in mt_cols:
            try:
                op.drop_index(op.f('ix_membership_types_tebex_package_id'), table_name='membership_types')
            except Exception:
                pass
            op.drop_column('membership_types', 'tebex_package_id')

    if 'memberships' in tables:
        m_cols = [c['name'] for c in insp.get_columns('memberships')]
        if 'tebex_transaction_id' in m_cols:
            try:
                op.drop_index(op.f('ix_memberships_tebex_transaction_id'), table_name='memberships')
            except Exception:
                pass
            op.drop_column('memberships', 'tebex_transaction_id')
        if 'tebex_subscription_id' in m_cols:
            try:
                op.drop_index(op.f('ix_memberships_tebex_subscription_id'), table_name='memberships')
            except Exception:
                pass
            op.drop_column('memberships', 'tebex_subscription_id')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('membership_types', sa.Column('base_price_usd', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False))
    op.create_table('bans',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('steam_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('reason', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('rcon_sync_status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('banned_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['steam_id'], ['players.steam_id'], name=op.f('bans_steam_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('bans_pkey'))
    )
    op.create_index(op.f('ix_bans_steam_id'), 'bans', ['steam_id'], unique=False)
    op.create_table('payment_records',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('steam_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('discord_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('package_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('package_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.0'), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=10), server_default=sa.text("'USD'::character varying"), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=30), server_default=sa.text("'COMPLETED'::character varying"), autoincrement=False, nullable=False),
    sa.Column('raw_payload', sa.TEXT(), server_default=sa.text("'{}'::text"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('payment_records_pkey'))
    )
    op.create_index(op.f('ix_payment_records_transaction_id'), 'payment_records', ['transaction_id'], unique=True)
    op.create_index(op.f('ix_payment_records_steam_id'), 'payment_records', ['steam_id'], unique=False)
    op.create_index(op.f('ix_payment_records_status'), 'payment_records', ['status'], unique=False)
    op.create_index(op.f('ix_payment_records_package_id'), 'payment_records', ['package_id'], unique=False)
    op.create_index(op.f('ix_payment_records_event_type'), 'payment_records', ['event_type'], unique=False)
    op.create_index(op.f('ix_payment_records_discord_id'), 'payment_records', ['discord_id'], unique=False)
    # ### end Alembic commands ###
