"""Add quotas and rcon_sync_status

Revision ID: db3ec4dfb58e
Revises: 6c53688397d0
Create Date: 2026-09-13 15:15:31.496715

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'db3ec4dfb58e'
down_revision: str | Sequence[str] | None = '6c53688397d0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('membership_type_configs',
    sa.Column('membership_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('max_quota', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('membership_type')
    )
    op.add_column('memberships', sa.Column('rcon_sync_status', sqlmodel.sql.sqltypes.AutoString(), server_default='PENDING', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memberships', 'rcon_sync_status')
    op.drop_table('membership_type_configs')
    # ### end Alembic commands ###
